### ISSUE TITLE
KKFP/KeFS atem error Error: Number too big: 80 > 3

### ISSUE THREAD

**Issue by filiphanes** [Sofie-Automation/sofie-atem-connection#89]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Throwing error while parsing commands KKFP and KeFS.
I am using ATEM Television Studio, firmware version 8.2.3

* **Other information** 
```
COMMAND KKFP(60) <Buffer 00 3c 59 70 4b 4b 46 50 50 16 42 4c 4b 00 01 28 01 00 01 00 01 00 12 01 00 2c a2 80 49 6e 50 72 00 01 54 69 74 75 6c 6b 79 00 00 00 50 4f 0b 90 50 13 ... 10 more bytes>
atem error Error: Number too big: 80 > 3
    at Object.parseNumberBetween (/Users/fhanes/projects/atem-live-controller/node_modules/.pnpm/registry.npmjs.org/atem-connection/1.3.3/node_modules/atem-connection/dist/lib/atemUtil.js:28:19)
    at MixEffectKeyFlyKeyframeGetCommand.deserialize (/Users/fhanes/projects/atem-live-controller/node_modules/.pnpm/registry.npmjs.org/atem-connection/1.3.3/node_modules/atem-connection/dist/commands/MixEffects/Key/MixEffectKeyFlyKeyframeGetCommand.js:11:35)
    at AtemSocket._parseCommand (/Users/fhanes/projects/atem-live-controller/node_modules/.pnpm/registry.npmjs.org/atem-connection/1.3.3/node_modules/atem-connection/dist/lib/atemSocket.js:159:21)
```

```
COMMAND KeFS(16) <Buffer 00 10 50 72 4b 65 46 53 61 63 6b 00 50 bc 4e 90>
atem error Error: Number too big: 97 > 3
    at Object.parseNumberBetween (/Users/fhanes/projects/atem-live-controller/node_modules/.pnpm/registry.npmjs.org/atem-connection/1.3.3/node_modules/atem-connection/dist/lib/atemUtil.js:28:19)
    at MixEffectKeyFlyPropertiesGetCommand.deserialize (/Users/fhanes/projects/atem-live-controller/node_modules/.pnpm/registry.npmjs.org/atem-connection/1.3.3/node_modules/atem-connection/dist/commands/MixEffects/Key/MixEffectKeyFlyPropertiesGetCommand.js:11:35)
    at AtemSocket._parseCommand (/Users/fhanes/projects/atem-live-controller/node_modules/.pnpm/registry.npmjs.org/atem-connection/1.3.3/node_modules/atem-connection/dist/lib/atemSocket.js:159:21)
```

```
COMMAND KKFP(60) <Buffer 00 3c 00 02 4b 4b 46 50 00 2c 00 01 49 6e 50 72 00 02 56 69 64 65 6f 20 50 43 00 00 50 13 08 34 00 10 08 34 4d 50 56 49 44 00 00 00 00 02 00 02 00 00 ... 10 more bytes>
atem error Error: Number too big: 44 > 3
    at Object.parseNumberBetween (/Users/fhanes/projects/atem-live-controller/node_modules/.pnpm/registry.npmjs.org/atem-connection/1.3.3/node_modules/atem-connection/dist/lib/atemUtil.js:28:19)
    at MixEffectKeyFlyKeyframeGetCommand.deserialize (/Users/fhanes/projects/atem-live-controller/node_modules/.pnpm/registry.npmjs.org/atem-connection/1.3.3/node_modules/atem-connection/dist/commands/MixEffects/Key/MixEffectKeyFlyKeyframeGetCommand.js:12:41)
    at AtemSocket._parseCommand (/Users/fhanes/projects/atem-live-controller/node_modules/.pnpm/registry.npmjs.org/atem-connection/1.3.3/node_modules/atem-connection/dist/lib/atemSocket.js:159:21)
```

**Comment by Julusian** [comment]
This is a known problem #69, that has been improved in the 2.0.0 prerelease builds.
On this model those particular errors are safe to ignore (the atem sends gibberish for an unsupported feature) at connection. As long as they dont happen later on then it is fine
